### ISSUE TITLE
Detect enums in dashed strings

### ISSUE THREAD

**Issue by artisologic** [nmsmith22389/vscode-incrementor#16]
First of all, I ❤️ the idea behind this extension.
I use this kind of control all the time in the Chrome Devtools and it's nice to have a matching behaviour inside the editor itself.

I have setup a new enum that would be really useful for CSS box model properties:

```json
[
	"top",
	"right",
	"bottom",
	"left"
]
```

It works only if used in directly matching properties like:

```css
.someClass {
	position: relative;
	top: 3px;
}
```

Putting the cursor on the `top` property, and hitting the shortcut will cycle as expected.
However I would love if it could work for the other ton of css properties that have these positional properties in their name. Here are some examples:

```css
.someClass {
	border-bottom: 1px solid black;
	margin-left: 5px;
	padding-right: 10px;
	...
}
```

There are loads of these and it would be super useful to be able to quickly switch the direction using your extension.

From what I read, an enum value cannot start with a `-` so it means I can't create another enum like so:

```json
[
	"-top",
	"-right",
	"-bottom",
	"-left"
]
```

Not sure if the limitation is what is causing the fact it is not detecting the enum in a dashed string though, hopefully this is something that can be fixed easily!

Thanks!
